---
title: "KNN2.Rmd"
author: "Kristan D Ramirez"
date: "2/11/2020"
output: word_document
---

# K-NN
```{r}
data <- read.csv('/Users/kris/Documents/pima.csv')

# Review data to find target variable; type. Variable 8
#data

# Review number of observations for type: 132 No, 68 Yes.
table(data$type)

# Yes and No for Diabetes converted to a percentage. 
round(prop.table(table(data$type))*100, digits=1) # 66% without Diabetes, 34 w/ Diabetes.

# Target variable is Type; variable 8, thus lets take out and noramalize the remaining data.
new_data <- data[-8]

```

## Normalize Data.
```{r}
# Scale is important, so let's normalize prior to moving to knn classifier. 
# Here we see that the units are far apart.  
str(new_data) # 200 obs, 7 var.
summary(new_data[c("npreg", "glu", "bp")])


# Normaalize function:
# We only apply to variables 2:31 since 1 is our target variable (factor)

normalize <- function(x){
  return((x-min(x))/(max(x)-min(x)))
}

new_data_n <- as.data.frame(lapply(new_data[1:7], normalize))

head(new_data_n)


```
# Add type variable back in after normalization.
```{r}

# adding type back in to data frame.
new_data_n2 <- cbind(new_data_n, type = data$type)
#t(t(names(new_data_n2))) # Now variable 8. 

  
set.seed(123)

# Set 70 percent of data into training data set, and 30 percent into testing data set.
idx <- sample(c("train", "test"), nrow(new_data_n2),
              replace=TRUE, prob = (c(70, 30)))


trainSet<-new_data_n2[idx=="train", 1:7]
testSet<-new_data_n2[idx=="test",1:7]


# Compose "type" training labels
data.trainLabels <-new_data_n2[idx=="train", 8]
# Compose "type" test labels
data.testLabels <-new_data_n2[idx=="test", 8]
```

#Test for best K.

###### K= 17: 69% accuracy. 

```{r}
library(class)

predict <-knn(train = trainSet, test=testSet, cl=data.trainLabels, k=17)


#install.packages("gmodels")
#library(gmodels)

#CrossTable(x=data.testLabels, y= predict)
library(caret)
confusionMatrix(data.testLabels, predict)
```
###### K= 18: 69% accuracy
```{r}
library(class)

predict <-knn(train = trainSet, test=testSet, cl=data.trainLabels, k=18)


#install.packages("gmodels")
#library(gmodels)

#CrossTable(x=data.testLabels, y= predict)
library(caret)
confusionMatrix(data.testLabels, predict)

```
###### K= 19: 69% accuracy
```{r}
library(class)

predict <-knn(train = trainSet, test=testSet, cl=data.trainLabels, k=19)


#install.packages("gmodels")
#library(gmodels)

#CrossTable(x=data.testLabels, y= predict)
library(caret)
confusionMatrix(data.testLabels, predict)

```
###### K= 20: 69% accuracy
```{r}
library(class)

predict <-knn(train = trainSet, test=testSet, cl=data.trainLabels, k=20)


#install.packages("gmodels")
#library(gmodels)

#CrossTable(x=data.testLabels, y= predict)
library(caret)
confusionMatrix(data.testLabels, predict)

```

# Best k = 17. All of the following Ks TP + TN/ Total equaled the same; (.69).
